version: '3.8'

services:
  vllm-rag:
    image: vllm/vllm-openai:v0.10.2
    container_name: vllm-rag-server
    network_mode: host
    volumes:
      - /your/path/to/models:/models
    environment:
      - HF_HOME=/models/.cache
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    command: >
      --model openai/gpt-oss-20b
      --host 0.0.0.0
      --port 8004
      --tensor-parallel-size 1
      --gpu-memory-utilization 0.9